### ISSUE TITLE
filter() should verify that host/key config vars are not empty

### ISSUE THREAD

**Issue by danmarsden** [agrowe/moodle-filter_camo#1]
Hi Alex, looks like a nice simple plugin - I'd suggest adding some validation to the filter() function to make sure that the host/key config vars aren't empty before running them through the filter.

I'd also be tempted to leave the default host empty rather than using an invalid placeholder url (https://camo.example.com) and forcing the admin to configure it properly.

**Comment by alex-rowe** [comment]
Thanks Dan,
The latest commit fixes all issues from the codechecker plugin and adds in some validation around the host and key values.

Thanks
Alex
